#lang sicp

(define (assoc key records)
  (cond ((null? records) false)
        ((equal? key (caar records)) (car records))
        (else (assoc key (cdr records)))))
(define (make-table)
  (let ((local-table (list '*table*)))
    (define (lookup key-1 key-2)
      (let ((subtable (assoc key-1 (cdr local-table))))
        (if subtable
            (let ((record (assoc key-2 (cdr subtable))))
              (if record
                  (cdr record)
                  false))
            false)))
    (define (insert! key-1 key-2 value)
      (let ((subtable (assoc key-1 (cdr local-table))))
        (if subtable
            (let ((record (assoc key-2 (cdr subtable))))
              (if record
                  (set-cdr! record value)
                  (set-cdr! subtable
                            (cons (cons key-2 value)
                                  (cdr subtable)))))
            (set-cdr! local-table
                      (cons (list key-1
                                  (cons key-2 value))
                            (cdr local-table)))))
      'ok)
    (define (dispatch m)
      (cond ((eq? m 'lookup-proc) lookup)
            ((eq? m 'insert-proc!) insert!)
            (else (error "Unknown operation -- TABLE" m))))
    dispatch))
(define operation-table (make-table))
(define get (operation-table 'lookup-proc))
(define put (operation-table 'insert-proc!))
(define (attach-tag type-tag contents)
  (cons type-tag contents))
(define (type-tag datum)
  (if (pair? datum)
      (car datum)
      (error "Bad tagged datum: TYPE-TAG" datum)))
(define (contents datum)
  (if (pair? datum)
      (cdr datum)
      (error "Bad tagged datum: CONTENTS" datum)))
(define (apply-generic op . args)
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
          (apply proc (map contents args))
          (error
           "No method for these types -- APPLY-GENERIC"
           (list op type-tags))))))

(define (add x y) (apply-generic 'add x y))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))
(define (square x) (apply-generic 'mul x x))
(define (gcd x y) (apply-generic 'gcd x y)) ; integer only
(define (sqroot x) (apply-generic 'sqroot x)) ; integer and rational
(define (arctan x) (apply-generic 'arctan x)) ; integer and rational
(define (cosine x) (apply-generic 'cosine x)) ; integer and rational
(define (sine x) (apply-generic 'sine x)) ; integer and rational

(define (install-integer-package)
  (define (mak-int n) (round n))
  (define (add-int x y) (+ x y))
  (define (sub-int x y) (- x y))
  (define (mul-int x y) (* x y))
  (define (div-int x y) (/ x y))
  (define (gcd-int x y)
    (if (= y 0) x
        (gcd-int y (remainder x y))))
  (define (sqroot-int x)
    (let ((exact-root (inexact->exact (sqrt x))))
      (rational (numerator exact-root) (denominator exact-root))))
  
  (define (tag x) (attach-tag 'integer x))
  (put 'mak 'integer (lambda (n) (tag (mak-int n))))
  (put 'add '(integer integer) (lambda (x y) (tag (add-int x y))))
  (put 'sub '(integer integer) (lambda (x y) (tag (sub-int x y))))
  (put 'mul '(integer integer) (lambda (x y) (tag (mul-int x y))))
  (put 'div '(integer integer) (lambda (x y) (tag (div-int x y))))
  (put 'gcd '(integer integer) (lambda (x y) (tag (gcd-int x y))))
  (put 'sqroot '(integer) (lambda (x) (tag (sqroot-int x))))
  'done)
(install-integer-package)
(define (integer n) ((get 'mak 'integer) n))

(define (install-rational-package)
  (define (mak-rat n d)
    (let ((g (gcd n d)))
      (cons (div n g) (div d g))))
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (add-rat x y)
    (mak-rat (add (mul (numer x) (denom y)) (mul (numer y) (denom x)))
             (mul (denom x) (denom y))))
  (define (sub-rat x y)
    (mak-rat (sub (mul (numer x) (denom y)) (mul (numer y) (denom x)))
             (mul (denom x) (denom y))))
  (define (mul-rat x y)
    (mak-rat (mul (numer x) (numer y))
             (mul (denom x) (denom y))))
  (define (div-rat x y)
    (mak-rat (mul (numer x) (denom y))
             (mul (numer y) (denom x))))
  (define (sqroot-rat x)
    (let ((inexact-x (exact->inexact (/ (numer x) (denom x)))))
      (let ((exact-root (inexact->exact (sqrt inexact-x))))
        (rational (numerator exact-root) (denominator exact-root)))))
  
  (define (tag x) (attach-tag 'rational x))
  (put 'mak 'rational (lambda (n d) (tag (mak-rat n d))))
  (put 'add '(rational rational) (lambda (x y) (tag (add-rat x y))))
  (put 'sub '(rational rational) (lambda (x y) (tag (sub-rat x y))))
  (put 'mul '(rational rational) (lambda (x y) (tag (mul-rat x y))))
  (put 'div '(rational rational) (lambda (x y) (tag (div-rat x y))))
  (put 'sqroot '(rational) (lambda (x) (tag (sqroot-rat x))))
  'done)
(install-rational-package)
(define (rational n d) ((get 'mak 'rational) n d))

(define (install-complex-package)
  (define (install-rectangular-package)
    (define (mak x y) (cons x y))
    (define (real-part z) (car z))
    (define (imag-part z) (cdr z))
    (define (magnitude z) (sqroot (add (square (real-part z))
                                       (square (imag-part z)))))
    (define (angle z) (arctan (div (imag-part z) (real-part z))))
    (define (tag x) (attach-tag 'rectangular x))
    (put 'real-part '(rectangular) real-part)
    (put 'imag-part '(rectangular) imag-part)
    (put 'magnitude '(rectangular) magnitude)
    (put 'angle '(rectangular) angle)
    (put 'mak 'rectangular (lambda (x y) (tag (mak x y))))
    'done)
  (install-rectangular-package)
  (define (rectangular x y) ((get 'mak 'rectangular) x y))
  (define (install-polar-package)
    (define (mak r a) (cons r a))
    (define (magnitude z) (car z))
    (define (angle z) (cdr z))
    (define (real-part z) (mul (magnitude z) (cosine (angle z))))
    (define (imag-part z) (mul (magnitude z) (sine (angle z))))
    (define (tag x) (attach-tag 'polar x))
    (put 'real-part '(polar) real-part)
    (put 'imag-part '(polar) imag-part)
    (put 'magnitude '(polar) magnitude)
    (put 'angle '(polar) angle)
    (put 'mak 'polar (lambda (r a) (tag (mak r a))))
    'done)
  (install-polar-package)
  (define (polar r a) ((get 'mak 'polar) r a))

  (define (real-part x) (apply-generic 'real-part x))
  (define (imag-part x) (apply-generic 'imag-part x))
  (define (magnitude x) (apply-generic 'magnitude x))
  (define (angle x) (apply-generic 'angle x))
  (define (add x y) (rectangular (add (real-part x) (real-part y))
                                 (add (imag-part x) (imag-part y))))
  (define (sub x y) (rectangular (sub (real-part x) (real-part y))
                                 (sub (imag-part x) (imag-part y))))
  (define (mul x y) (polar (mul (magnitude x) (magnitude y))
                           (add (angle x) (angle y))))
  (define (div x y) (polar (div (magnitude x) (magnitude y))
                           (sub (angle x) (angle y))))
  (define (tag x) (attach-tag 'complex x))
  (put 'mak-rec 'complex rectangular)
  (put 'mak-pol 'complex polar)
  (put 'real-part '(complex) real-part)
  (put 'imag-part '(complex) imag-part)
  (put 'magnitude '(complex) magnitude)
  (put 'angle '(complex) angle)
  (put 'add '(complex complex) (lambda (x y) (tag (add x y))))
  (put 'sub '(complex complex) (lambda (x y) (tag (sub x y))))
  (put 'mul '(complex complex) (lambda (x y) (tag (mul x y))))
  (put 'div '(complex complex) (lambda (x y) (tag (div x y))))
  'done)
(install-complex-package)
(define (complex-rectangular x y) ((get 'mak-rec 'complex) x y))
(define (complex-polar r a) ((get 'mak-pol 'complex) r a))