#lang sicp

(define (accumulate op initial sequence)
  (if (null? sequence)
      initial
      (op (car sequence)
          (accumulate op initial (cdr sequence)))))
(define (filter predicate sequence)
  (cond ((null? sequence) '())
        ((predicate (car sequence))
         (cons (car sequence)
               (filter predicate (cdr sequence))))
        (else (filter predicate (cdr sequence)))))
(define (flatmap proc seq)
  (accumulate append nil (map proc seq)))
(define (enumerate-interval low high)
  (if (> low high)
      '()
      (cons low (enumerate-interval (+ low 1) high))))

(define (unique-pairs n)
  (flatmap (lambda (pair)
             (map (lambda (k)
                    (cons k pair))
                  (enumerate-interval 1 (- (car pair) 1))))
           (flatmap (lambda (i)
                      (map (lambda (j) (list j i))
                           (enumerate-interval 1 (- i 1))))
                    (enumerate-interval 1 n))))

(define (s-sum-pairs n s)
  (define (s-sum? pair)
    (= s (accumulate + 0 pair)))
  (filter s-sum?
          (unique-pairs n)))