#lang sicp
(#%require sicp-pict)

(define (right-split painter n)
  (if (= n 0)
      painter
      (let ((smaller (right-split painter (- n 1))))
        (beside painter (below smaller smaller)))))
(define (up-split painter n)
  (if (= n 0)
      painter
      (let ((smaller (up-split painter (- n 1))))
        (below painter (beside smaller smaller)))))
(define (square-of-four tl tr bl br)
  (lambda (painter)
    (let ((top (beside (tl painter) (tr painter)))
          (bottom (beside (bl painter) (br painter))))
      (below bottom top))))

;a)
(define wave
  (segments->painter (list (make-segment (make-vect 0.4 1.0) (make-vect 0.35 0.85))
                           (make-segment (make-vect 0.35 0.85) (make-vect 0.4 0.64))
                           (make-segment (make-vect 0.4 0.65) (make-vect 0.25 0.65))
                           (make-segment (make-vect 0.25 0.65) (make-vect 0.15 0.6))
                           (make-segment (make-vect 0.15 0.6) (make-vect 0.0 0.85))
                           (make-segment (make-vect 0.0 0.65) (make-vect 0.15 0.35))
                           (make-segment (make-vect 0.15 0.35) (make-vect 0.25 0.6))
                           (make-segment (make-vect 0.25 0.6) (make-vect 0.35 0.5))
                           (make-segment (make-vect 0.35 0.5) (make-vect 0.25 0.0))
                           (make-segment (make-vect 0.6 1.0) (make-vect 0.65 0.85))
                           (make-segment (make-vect 0.65 0.85) (make-vect 0.6 0.65))
                           (make-segment (make-vect 0.6 0.65) (make-vect 0.75 0.65))
                           (make-segment (make-vect 0.75 0.65) (make-vect 1.0 0.3))
                           (make-segment (make-vect 1.0 0.15) (make-vect 0.6 0.5))
                           (make-segment (make-vect 0.6 0.5) (make-vect 0.75 0.0))
                           (make-segment (make-vect 0.4 0.0) (make-vect 0.5 0.3))
                           (make-segment (make-vect 0.6 0.0) (make-vect 0.5 0.3))
                           (make-segment (make-vect 0.5 0.5) (make-vect 0.8 0.8)))))

;b)
(define (corner-split painter n)
  (if (= n 0)
      painter
      (let ((up (up-split painter (- n 1)))
            (right (right-split painter (- n 1))))
        (let ((top-left up)
              (bottom-right right)
              (corner (corner-split painter (- n 1))))
          (beside (below painter top-left)
                  (below bottom-right corner))))))

;c)
(define (square-limit painter n)
  (let ((combine4 (square-of-four identity flip-horiz flip-vert rotate180)))
    (combine4 (corner-split painter n))))