#lang sicp

(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
(define (make-segment start end)
  (cons start end))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))

(define (make-rectangle point1 point2)
  (cons point1 point2))
(define (horizontal-rectangle rectangle)
  (abs (- (x-point (car rectangle)) (x-point (cdr rectangle)))))
(define (vertical-rectangle rectangle)
  (abs (- (y-point (car rectangle)) (y-point (cdr rectangle)))))

;(define (make-rectangle segment1 segment2)
;  (cons segment1 segment2))
;(define (horizontal-rectangle rectangle)
;  (abs (- (x-point (start-segment (car rectangle))) (x-point (end-segment (car rectangle))))))
;(define (horizontal-rectangle rectangle)
;  (abs (- (y-point (start-segment (cdr rectangle))) (y-point (end-segment (cdr rectangle))))))

(define (perimeter-rectangle rectangle)
  (* 2 (+ (horizontal-rectangle rectangle) (vertical-rectangle rectangle))))
(define (area-rectangle rectangle)
  (* (horizontal-rectangle rectangle) (vertical-rectangle rectangle)))