#lang sicp

(define (make-mobile left right)
  (list left right))
(define (make-branch length structure)
  (list length structure))

;a)
(define (left-branch mobile) (car mobile))
(define (right-branch mobile) (car (cdr mobile)))
(define (branch-length branch) (car branch))
(define (branch-structure branch) (car (cdr branch)))

;b)
(define (total-weight mobile)
  (define (weight branch)
    (cond ((not (pair? (branch-structure branch))) (branch-structure branch))
          (else (total-weight (branch-structure branch)))))
  (+ (weight (left-branch mobile)) (weight (right-branch mobile))))

;c)
(define (balanced? mobile)
  (cond ((not (pair? mobile)) #t)
        (else (let ((l (left-branch mobile))
                    (r (right-branch mobile)))
                (and (balanced? (branch-structure l))
                     (balanced? (branch-structure r))
                     (= (* (branch-length l) (total-weight (branch-structure l)))
                        (* (branch-length r) (total-weight (branch-structure r)))))))))

;d)
;(define (make-mobile left right)
;  (cons left right))
;(define (make-branch length structure)
;  (cons length structure))
;(define (left-branch mobile) (car mobile))
;(define (right-branch mobile) (cdr mobile))
;(define (branch-length branch) (car branch))
;(define (branch-structure branch) (cdr branch))