#lang sicp

(define (make-interval a b) (cons a b))
(define (upper-bound x) (cdr x))
(define (lower-bound x) (car x))
(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
                 (+ (upper-bound x) (upper-bound y))))
(define (sub-interval x y)
  (add-interval x
                (make-interval (- (upper-bound y))
                               (- (lower-bound y)))))
(define (mul-interval x y)
  (let ((a (lower-bound x))
        (b (upper-bound x))
        (c (lower-bound y))
        (d (upper-bound y)))
    (cond ((and (> a 0) (> c 0)) (make-interval (* a c) (* b d)))
          ((and (> a 0) (<= c 0) (> d 0)) (make-interval (* b c) (* b d)))
          ((and (> a 0) (<= d 0)) (make-interval (* b c) (* a d)))
          ((and (<= a 0) (> b 0) (> c 0)) (make-interval (* a d) (* b d)))
          ((and (<= a 0) (> b 0) (<= c 0) (> d 0)) (make-interval (min (* a d) (* b c)) (max (* a c) (* b d))))
          ((and (<= a 0) (> b 0) (<= d 0)) (make-interval (* b c) (* a c)))
          ((and (<= b 0) (> c 0)) (make-interval (* a d) (* b c)))
          ((and (<= b 0) (<= c 0) (> d 0)) (make-interval (* a d) (* a c)))
          ((and (<= b 0) (<= d 0)) (make-interval (* b d) (* a c))))))
(define (div-interval x y)
  (if (< (* (lower-bound y) (upper-bound y)) 0)
      (error "divisor spans zero")
      (mul-interval x
                    (make-interval (/ 1.0 (upper-bound y))
                                   (/ 1.0 (lower-bound y))))))
(define (make-center-percent c p)
  (make-interval (- c (* c p)) (+ c (* c p))))
(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (percent i)
  (/ (/ (- (upper-bound i) (lower-bound i)) 2) (center i)))

(define (par1 r1 r2)
  (div-interval (mul-interval r1 r2)
                (add-interval r1 r2)))
(define (par2 r1 r2)
  (let ((one (make-interval 1 1)))
    (div-interval one
                  (add-interval (div-interval one r1)
                                (div-interval one r2)))))

(define r1 (make-interval 1.999 2.001))
(define r2 (make-interval 2.998 3.002))
(par1 r1 r2) ;(1.1978816709974016 . 1.202121673003802)
(par2 r1 r2) ;(1.1993199919951971 . 1.200679992004797)

(define A (make-interval 9.9 10.1))
(define B (make-interval 19.85 20.15))
(div-interval A A) ;(0.9801980198019803 . 1.02020202020202)
(div-interval A B) ;(0.49131513647642683 . 0.508816120906801)