#lang sicp

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops)
    "CALL THE COPS!")
  (define (dispatch attempt m)
    (let ((monitor 0))
      (if (eq? attempt password)
          (begin (set! monitor 0)
                 (cond ((eq? m 'withdraw) withdraw)
                       ((eq? m 'deposit) deposit)
                       (else (error "Unknown request: MAKE-ACCOUNT"
                                    m))))
          (if (< monitor 6)
              (begin (set! monitor (inc monitor)) "Incorrect password")
              (call-the-cops)))))
  dispatch)