#lang sicp

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch attempt m)
    (if (eq? attempt password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request: MAKE-ACCOUNT"
                           m)))
        "Incorrect password"))
  dispatch)

(define (make-joint account old-password new-password)
  (lambda (attempt m)
    (if (eq? attempt new-password)
        (account old-password m)
        (account attempt m))))