#lang sicp

(define (make-tree key value left right)
  (list key value left right))
(define (key tree) (car tree))
(define (value tree) (cadr tree))
(define (left tree) (caddr tree))
(define (right tree) (cadddr tree))
(define (set-value! tree v) (set-car! (cdr tree) v))
(define (set-left! tree left) (set-car! (cddr tree) left))
(define (set-right! tree right) (set-car! (cdddr tree) right))

(define (make-table)
  (let ((root '()))
    (define (lookup key)
      (define (iter node)
        (cond ((null? node) false)
              ((equal? key (key node)) (value node))
              ((< key (key node)) (iter (left node)))
              (else (iter (right node)))))
      (iter root))
    (define (insert! key value)
      (define (iter node)
        (cond ((equal? key (key node)) (set-value! node value))
              ((< key (key node))
               (if (null? (left node))
                   (set-left! node (make-tree key value '() '()))
                   (iter (left node))))
              (else
               (if (null? (right node))
                   (set-right! node (make-tree key value '() '()))
                   (iter (right node))))))
      (if (null? root)
          (set! root (make-tree key value '() '()))
          (iter root))
      'ok)
    (define (dispatch m)
      (cond ((eq? m 'lookup-proc) lookup)
            ((eq? m 'insert-proc!) insert!)
            (else (error "Unknown operation: TABLE" m))))
    dispatch))