#lang sicp

(define (make-serializer)
  (let ((mutex (make-mutex)))
    (lambda (p)
      (define (serialized-p . args)
        (mutex 'acquire)
        (let ((val (apply p args)))
          (mutex 'release)
          val))
      serialized-p)))

(define (make-mutex)
  (let ((cell (list false)))
    (define (the-mutex m)
      (cond ((eq? m 'acquire)
             (if (test-and-set! cell)
                 (the-mutex 'acquire)))
            ((eq? m 'release) (clear! cell))))
    the-mutex))
(define (clear! cell) (set-car! cell false))
(define (test-and-set! cell)
  (if (car cell) true (begin (set-car! cell true) false)))

;a)
(define (make-semaphore n)
  (let ((mutex (make-mutex)))
    (define (the-semaphore m)
      (cond ((eq? m 'acquire)
             (mutex 'acquire)
             (if (> n 0)
                 (begin (set! n (dec n))
                        (mutex 'release))
                 (begin (mutex 'release)
                        (the-semaphore 'acquire))))
            ((eq? m 'release)
             (mutex 'acquire)
             (set! n (inc n))
             (mutex 'release))))
    the-semaphore))

;b)
;(define (make-semaphore n)
;  (let ((cell (list false)))
;    (define (the-semaphore m)
;      (cond ((eq? m 'acquire)
;             (if (test-and-set! cell)
;                 (the-semaphore 'acquire))
;             (if (> n 0)
;                 (begin (set! n (dec n))
;                        (clear! cell))
;                 (begin (clear! cell)
;                        (the-semaphore 'acquire))))
;            ((eq? m 'release)
;             (if (test-and-set! cell)
;                 (the-semaphore 'release))
;             (set! n (inc n))
;             (clear! cell))))
;    the-semaphore))