#lang sicp

(define (divides? a b)
  (= (remainder b a) 0))
(define (smallest-divisor n)
  (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (* test-divisor test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))))
(define (prime? n)
  (= n (smallest-divisor n)))

(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))

(define (next-odd n) (if (odd? n) (+ n 2) (+ n 1)))
(define (search-for-primes start)
  (search-primes-iter (next-odd start) 3))
(define (search-primes-iter start count)
  (cond ((= count 0) (newline))
        ((prime? start) (timed-prime-test start) (search-primes-iter (next-odd start) (- count 1)))
        (else (search-primes-iter (next-odd start) count))))